/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated.transport'
import { Route as AuthenticatedRefiningRouteImport } from './routes/_authenticated.refining'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated.prices'
import { Route as AuthenticatedGoldRouteImport } from './routes/_authenticated.gold'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCraftingRouteImport } from './routes/_authenticated.crafting'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefiningRoute = AuthenticatedRefiningRouteImport.update({
  id: '/refining',
  path: '/refining',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoldRoute = AuthenticatedGoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCraftingRoute = AuthenticatedCraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crafting': typeof AuthenticatedCraftingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gold': typeof AuthenticatedGoldRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refining': typeof AuthenticatedRefiningRoute
  '/transport': typeof AuthenticatedTransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crafting': typeof AuthenticatedCraftingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gold': typeof AuthenticatedGoldRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refining': typeof AuthenticatedRefiningRoute
  '/transport': typeof AuthenticatedTransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/crafting': typeof AuthenticatedCraftingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gold': typeof AuthenticatedGoldRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/refining': typeof AuthenticatedRefiningRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crafting'
    | '/dashboard'
    | '/gold'
    | '/prices'
    | '/profile'
    | '/refining'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crafting'
    | '/dashboard'
    | '/gold'
    | '/prices'
    | '/profile'
    | '/refining'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/crafting'
    | '/_authenticated/dashboard'
    | '/_authenticated/gold'
    | '/_authenticated/prices'
    | '/_authenticated/profile'
    | '/_authenticated/refining'
    | '/_authenticated/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refining': {
      id: '/_authenticated/refining'
      path: '/refining'
      fullPath: '/refining'
      preLoaderRoute: typeof AuthenticatedRefiningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gold': {
      id: '/_authenticated/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof AuthenticatedGoldRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crafting': {
      id: '/_authenticated/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof AuthenticatedCraftingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCraftingRoute: typeof AuthenticatedCraftingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoldRoute: typeof AuthenticatedGoldRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRefiningRoute: typeof AuthenticatedRefiningRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCraftingRoute: AuthenticatedCraftingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoldRoute: AuthenticatedGoldRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRefiningRoute: AuthenticatedRefiningRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
